### PR TITLE
Image 2 registry

### LINKED ISSUE #12: WebApp invokes the Container Service Build
_As a DLHub user I want the container service to build a docker image based on my specification so I can find an image to run my model_

## Acceptance Criteria
Given I have a valid docker container specification JSON When I submit to the WebService Then the container service starts the build and the status of the container record will be _Building_

## Assumptions
1. Will invoke the container service `/build` operation. The payload will include the UUID of the container along with the container type (always docker) and the specification.
2. The WebService will have a `/containers/<uuid>/status` PUT operation to allow the Container service to update the status
3. To avoid problems with jobs running in multiple pods there can only be one instance of the container service

### PR DESCRIPTION
**Pull request by blue442**
Incorporating pushing the built image to a docker registry stored in the .env file. Also refines the `PUT` routes used to update the build status of the container with the webservice, improves the callback documentation provided by the swagger interface, and improves the documentation in the readme.

Closes #12

### CODE REVIEW

**Comment by blue442** [comment]
Updated to resolve perceived issues with integration (there could be more) - this should address #11 and #12 assuming the integration with the web service is successful, as well as #14 and #9.

**Comment by blue442** [comment]
@BenGalewsky updated messaging as discussed this morning has been integrated - note that the fastAPI documentation of the callback is grabbing the first possible value of the 'BuildStatus' enum, so while the documentation suggests that they will all return a build status of 'pending', I've verified that this is not the case. I'm not sure how to hardcode that enum value in the auto-generated docs :/

**Comment by blue442** [comment]
Okay @BenGalewsky - last issue to be resolved before merging to `dev` - the docker run command for the container service as it sits in the readme didn't work for me to run the service in a container locally:

1. The `funcx/container-service:dev` image was build from dev, so doesn't have the full functionality - I built a local instance (which we could describe) or update the referenced image
2. I needed the `run` command itself to map the `docker.sock` file, and the `.env` file:
```
docker run --rm -it \
	--env WEBSERVICE_URL=http://host.docker.internal:5000 \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(pwd)/.env:/opt/.env \
	-p 8000:8000 container_service:latest
```
3. I needed to change the permissions for the `docker.sock` file to run successfully:
```
$ docker exec -it -u root [container id] bash
$ chmod 777 /var/run/docker.sock
```

I suggest we include additional documentation for 2 and 3 (I'm happy to do that), don't have a strong preference on 1 - wanted to get your opinion(s) first.

**Review by BenGalewsky — APPROVED** [review]
Looks like we got it!

**Pull request merged**
